ALTER TABLE mandels ADD COLUMN IF NOT EXISTS title_mode INT NOT NULL DEFAULT 0;
ALTER TABLE mandels ADD COLUMN IF NOT EXISTS what TEXT NOT NULL DEFAULT '';
ALTER TABLE mandels ADD COLUMN IF NOT EXISTS before TEXT NOT NULL DEFAULT '';
ALTER TABLE mandels ADD COLUMN IF NOT EXISTS after TEXT NOT NULL DEFAULT '';
