CREATE TABLE IF NOT EXISTS marks (
    id serial NOT NULL PRIMARY KEY,
    mandela_id INT NOT NULL REFERENCES mandels(id) ON DELETE CASCADE ON UPDATE CASCADE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE SET DEFAULT ON UPDATE CASCADE,
    create_ts timestamptz NOT NULL DEFAULT now()
);
