[server]
port = 21000

[frontend]
domen = "http://ocean-mandela.info"

[postgres]
host = "localhost"
port = 5432
username = "ocean"
password = ""
database = "ocean"

[telegram_bot]
token = ""
url = "https://api.telegram.org"
channel = ""
admin_chat_id = ""
enabled = true
