[server]
port = 21000

    [server.ssl]
    key = "/home/../ssl/ocean.key"
    cert = "/home/../ssl/ocean.cert"

[postgres]
host = "localhost"
port = 5432
username = "ocean"
password = ""
database = "ocean"
