[server]
port = 21000
anonym_allowed = false

[server.ssl]
key = "/home/../ssl/ocean.key"
cert = "/home/../ssl/ocean.cert"

[frontend]
domen = "https://ocean-mandela.info"

[postgres]
host = "localhost"
port = 5432
username = "ocean"
password = ""
database = "ocean"

[telegram_bot]
token = ""
url = "https://api.telegram.org"
channel = ""
admin_chat_id = ""
enabled = true

[watchdog]
enabled = false
anonym_token = ""
